name: mac

on:
  push:
    branches:
    - port_macos
  pull_request:
    branches:
    - port_macos

permissions:
  contents: read  #  to fetch code (actions/checkout)

env:
  LANG: en_US.UTF-8
  LOCAL_BIN: ${{ github.workspace }}/.local/bin
  LD_LIBRARY_PATH: "/github/home/.hsthrift/lib"
  PKG_CONFIG_PATH: "/github/home/.hsthrift/lib/pkgconfig"

jobs: 
  build:
    runs-on: macos-15
    steps:
    - uses: actions/checkout@v4
    - name: Show disk space at start
      run: df -h
    - name: Free up disk space
      run: sudo rm -rf /usr/local/lib/android
    - name: Show disk space after freeing up
      run: df -h
    - name: Setup LOCAL_BIN environment
      run: |
        mkdir -p "$LOCAL_BIN"
        echo "$LOCAL_BIN" >> "$GITHUB_PATH"
    - name: Env
      run: env
    - name: Setup Haskell
      run: |
        curl --proto '=https' --tlsv1.2 -sSf "https://downloads.haskell.org/~ghcup/aarch64-apple-darwin-ghcup" -o "$LOCAL_BIN"/ghcup
        chmod +x "$LOCAL_BIN"/ghcup
        ghcup install cabal --set
        ghcup install ghc 9.2.8 --set
        echo "$HOME/.ghcup/bin" >> "$GITHUB_PATH"

    - name: Install system deps
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages install-system-deps --recursive hsthrift

    - name: Build boost
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests boost
    - name: Fetch openssl
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests openssl
    - name: Fetch ninja
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests ninja
    - name: Fetch cmake
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests cmake
    - name: Fetch double-conversion
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests double-conversion
    - name: Fetch fast_float
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests fast_float
    - name: Fetch fmt
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests fmt
    - name: Fetch gflags
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests gflags
    - name: Fetch glog
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests glog
    - name: Fetch googletest
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests googletest
    - name: Fetch libdwarf
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests libdwarf
    - name: Fetch libevent
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests libevent
    - name: Fetch lz4
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests lz4
    - name: Fetch snappy
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests snappy
    - name: Fetch zstd
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests zstd
    - name: Fetch autoconf
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests autoconf
    - name: Fetch automake
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests automake
    - name: Fetch libtool
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests libtool
    - name: Fetch libsodium
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests libsodium
    - name: Fetch xz
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests xz
    - name: Fetch folly
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests folly
    - name: Fetch fizz
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests fizz
    - name: Fetch wangle
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests wangle
    - name: Fetch mvfst
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests mvfst
    - name: Fetch fbthrift
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages fetch --no-tests fbthrift

    - name: Build boost
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests boost
    - name: Build openssl
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests openssl
    - name: Build ninja
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests ninja
    - name: Build cmake
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests cmake
    - name: Build double-conversion
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests double-conversion
    - name: Build fast_float
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests fast_float
    - name: Build fmt
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests fmt
    - name: Build gflags
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests gflags
    - name: Build glog
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests glog
    - name: Build googletest
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests googletest
    - name: Build libdwarf
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests libdwarf
    - name: Build libevent
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests libevent
    - name: Build lz4
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests lz4
    - name: Build snappy
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests snappy
    - name: Build zstd
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests zstd
    - name: Build autoconf
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests autoconf
    - name: Build automake
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests automake
    - name: Build libtool
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests libtool
    - name: Build libsodium
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests libsodium
    - name: Build xz
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --free-up-disk --no-tests xz
    - name: Build folly
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --no-tests folly
    - name: Build fizz
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --no-tests fizz
    - name: Build wangle
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --no-tests wangle
    - name: Build mvfst
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --no-tests mvfst
    - name: Build fbthrift
      run: python3 build/fbcode_builder/getdeps.py --allow-system-packages build --no-tests fbthrift

    - name: Install folly, fizz, wangle, fbthrift
      run: ./new_install_deps.sh
    - name: Add fbthrift/thrift1 to PATH
      run: echo "$HOME/.hsthrift/bin" >> "$GITHUB_PATH"
  
    - name: Populate hackage index
      run: cabal update
    - name: Generate C++ code from thrift files
      run: make thrift-cpp
    - name: Build everything up to thrift-compiler
      run: cabal build --project-file=ci.cabal.project exe:thrift-compiler
    - name: Generate Haskell code from thrift files
      run: make thrift-hs
    - name: Generate source distributions for all packages
      run: cabal sdist --project-file=ci.cabal.project all
    - name: Unpack source distributions in new directory
      run: |
        mkdir _sdists
        cd _sdists
        for f in $(ls ../dist-newstyle/sdist/*.tar.gz); do
          tar xzf $f;
        done
        cp ../ci-sdist.cabal.project cabal.project
        cd ..
    - name: Build all packages
      run: cabal build all
      working-directory: ./_sdists
    - name: Run testsuites
      run: cabal test mangle fb-util thrift-compiler thrift-lib thrift-tests thrift-server --keep-going
      working-directory: ./_sdists



      

      
